### ISSUE TITLE
line inversion in qcfs function activation

### ISSUE THREAD

**Issue by romain-pierre1** [putshua/SNN-conversion-QCFS#2]
Hello,

I believe there is a line inversion occuring in file modules.py at lines 69 and 70:
```python
class MyFloor(nn.Module):
    ...
    def forward(self, x):
        x = x / self.up
        x = torch.clamp(x, 0, 1) # line 69, should be line 70
        x = myfloor(x*self.t+0.5)/self.t # line 70, should be line 69
        x = x * self.up
        return x
```

Per the paper, clipping is done after the floor operation.

**Comment by putshua** [comment]
The inversion doesn't affect the forward function. There is only slightly differences when backward. Actually I have tested both two forms and the final performance is nearly the same.
To match with the paper, I will change this function in my code. Thanks for suggestion!
