### ISSUE TITLE
Conversion Error Analysis

### ISSUE THREAD

**Issue by jqjiang1999** [putshua/SNN-conversion-QCFS#6]
You mentioned **Quantization error** and **Unevenness error** of the third chapter in your paper, but I want to know how to understand this sentence ''the unevenness error will degenerate to the quantization error if v^l(T) is in the range of [0, θ^l]''

**Comment by putshua** [comment]
if v^l(T) is in the range of [0, θ^l], there will be no Unevenness error and only Quantization error. Detail proof is in Section A.3, Derivation of Equation 11.

**Comment by jqjiang1999** [comment]
Thanks for answering. So according to Derivation of Equation 11,  this will only exist Clipping error and Quantization error？

**Comment by putshua** [comment]
Under the ideal assumption that v^l(T) is in the range of [0, θ^l], yes.
