### ISSUE TITLE
非常具有进步性的工作！

### ISSUE THREAD

**Issue by Ikarosy** [putshua/SNN-conversion-QCFS#9]
我有个小问题，为了方便说明，沿用原论文里的符号含义。

通过shift操作使得QCFS函数 和 IF神经元输出输出相应关系函数（输入为z，输出为\phi）的 quantization error 的误差的期望值恒 为 0。
这样即使L 和 T不同，理论上也解释的通，并且实验Table S2也证明了L和T不同是可行的，并且最优的转换效果 并不经常出现在L=T的情况下。

但也正是存在这样的现象，我想问的是，当L=T的时候，QCFS函数和IF 神经元响应函数 应该是完全重合的、一样的，理论上完全解决了 quantization error （甚至不用通过计算什么误差的期望来证明）。按道理，所有的最优转换情况都应该出现在L=T的时候。但是从Table S2的结果来看并不是这样。这是为什么呢？ 是否是因为存在unevenness error这样的不确定误差导致的呢？

非常想听一下大佬的看法 ^_^

**Comment by putshua** [comment]
您好，
主要就是因为存在unevenness error这样的误差。理论和实验上在消除了unevenness误差之后就可以做到无损转换。
感谢你的关注！

Tong Bu

从 Windows 版邮件发送

发件人: Ikaros
发送时间: 2023年2月9日 1:36
收件人: putshua/SNN_conversion_QCFS
抄送: Subscribed
主题: [putshua/SNN_conversion_QCFS] 非常具有进步性的工作！ (Issue #9)

我有个小问题，为了方便说明，沿用原论文里的符号含义。
通过shift操作使得QCFS函数 和 IF神经元输出输出相应关系函数（输入为z，输出为\phi）的 quantization error 的误差的期望值恒 为 0。
这样即使L 和 T不同，理论上也解释的通，并且实验Table S2也证明了L和T不同是可行的，并且最优的转换效果 并不经常出现在L=T的情况下。
但也正是存在这样的现象，我想问的是，当L=T的时候，QCFS函数和IF 神经元响应函数 应该是完全重合的、一样的，理论上完全解决了 quantization error （甚至不用通过计算什么误差的期望来证明）。按道理，所有的最优转换情况都应该出现在L=T的时候。但是从Table S2的结果来看并不是这样。这是为什么呢？ 是否是因为存在unevenness error这样的不确定误差导致的呢？
非常想听一下大佬的看法 ^_^
